config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'
  resources :notes, :documents

  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
  belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :find_document, only: [:destroy]

  def index
    @documents = Document.where(user_id: current_user)
  end

  def new
    @document = current_user.documents.build
  end

  def create
    @document = current_user.documents.build(document_params)

    if @document.save
      redirect_to documents_path, notice: "The document #{@document.name} has been uploaded."
    else
      render 'new'
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_path, notice:  "The document #{@document.name} has been deleted."
  end

  private

  def find_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:name, :attachment)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.where(user_id: current_user)
  end

  def show
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/index.html.haml
- if !flash[:notice].blank?
  .alert.alert-info
    = flash[:notice]
#sidebar-wrapper
  %ul.sidebar-nav
    %li= link_to 'Notes', notes_path, class: "sidebar-brand"
    %li= link_to 'Documents', documents_path, class: "sidebar-brand"
    %li= link_to 'Settings', edit_user_registration_path, class: "sidebar-brand"
.wrapper_with_padding
  .tab-name Documents
  %button= link_to "New Document", new_document_path
  %br/
  %br/
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Download Link
        %th
    %tbody
      - @documents.each do |document|
        %tr
          %td= "#{document.name} - #{time_ago_in_words(document.created_at)}"
          %td= link_to "Download Document", document.attachment_url
          %td= button_to "Delete",  document, method: :delete, confirm: "Are you sure that you wish to delete #{document.name}?"

app/views/documents/new.html.haml
- if !@document.errors.empty?
  .alert.alert-error
    %ul
      - @document.errors.full_messages.each do |msg|
        %li= msg
.wrapper_with_padding
  .well
    = form_for @document, html: { multipart: true } do |f|
      = f.label :name
      = f.text_field :name
      = f.label :attachment
      = f.file_field :attachment
      = f.submit "Upload", class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Timekeeper | Your Online Group Notebook
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"}
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to image_tag( 'logo.svg'), root_path, id: "logo"
      %nav
        - if user_signed_in?
          = link_to "Notes", notes_path
          = link_to "Documents", documents_path
          = link_to "Settings", edit_user_registration_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path

  %p.notice= notice
  %p.alert= alert

  = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/notes/edit.html.haml
.wrapper_with_padding
  %h1 Edit Note

  = render 'form'

  = link_to "Cancel", note_path

app/views/notes/index.html.haml
.wrapper
  #sidebar-wrapper
    %ul.sidebar-nav
      %li= link_to 'Notes', notes_path, class: "sidebar-brand"
      %li= link_to 'Documents', documents_path, class: "sidebar-brand"
      %li= link_to 'Settings', edit_user_registration_path, class: "sidebar-brand"
.wrapper_with_padding
  #notes.clearfix
    .tab-name Notes
    %button= link_to "New Note", new_note_path
    %br/
    %br/
    - unless @notes.blank?
      - @notes.each do |note|
        %a{ href: (url_for [note])}
          .note
            %p.title= note.title
            %p.date= time_ago_in_words(note.created_at)
    - else
      %h2 Add a Note
      %p It appears you haven't created any notes yet... Lets fix that. Why don't you go ahead and create a new note.
      %button= link_to "New Note", new_note_path

app/views/notes/new.html.haml
.wrapper_with_padding
  %h1 Add A New Note

  = render 'form'
  = link_to "Cancel", notes_path

app/views/notes/show.html.haml
.wrapper_with_padding
  #note_show
    %h1.title= @note.title
    %p= simple_format(@note.content)

    .buttons
      = link_to "All Notes", notes_path, class: "button"
      = link_to "Edit", edit_note_path(@note), class: "button"
      = link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button"

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 TimeKeeper
    %p Your online group note keeper. Never forget an idea again.

    %button= link_to "Sign Up", new_user_registration_path

#faq
  .wrapper
    %h2 one workspace
    %h4  Imagine all your team communication in one place. That's TimeKeeper.
    .wrapper
      .faq
        %i.fa.fa-clock-o
        %h3 WHY TIMEKEEPER
        %p TimeKeeper displays your work in a clean, easy-to-browse dashboard. Easily gather everything that matters to keep your group on the same page.
      .faq
        %i.fa.fa-dropbox
        %h3 SHAREBOX
        %p TimeKeeper works well on mobile and showcases your shots front and center. Try the demo on your smartphone to see the mobile.
      .faq
        %i.fa.fa-bell
        %h3 NOTIFICATIONS
        %p TimeKeeper maximizes the focus on your work. Configurable notifications for desktop, mobile push and email keep you as informed as you’d like.
      .faq
        %i.fa.fa-cog
        %h3 CUSTOMIZABLE
        %p TimeKeeper keeps the interface minimal, it's simple to find what you're looking for. Forget wasting hours managing notes.

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 timekeeper
        %h3 Free
        %button= "Sign Up"
        %h4 Organize your group projects.
        %p Limited ShareBox storage<br>Keep everything together <br>Workspace for a single project
      .callout
        %h2 timekeeper
        %h3 Premium
        %button= "Go Premium"
        %h4 Upgrade to work smarter.
        %p Educational pricing<br>Sync across all devices<br>Workspace for daily projects
      .callout
        %h2 timekeeper
        %h3 Enterprise
        %button= "Get Started"
        %h4 Get TimeKeeper for the team.
        %p All of Evernote Free <br>Offline access to projects<br>Centralized administration

#bottom_cta
  .wrapper
    %h2 Forget wasting hours managing notes
    %button= link_to "Get Started Now", new_user_registration_path

%footer
  %p &copy; Timekeeper